### ISSUE TITLE
nacos连接上去了，但没有显示服务调用信息

### ISSUE THREAD

**Issue by MarvinYu** [qiaolin-li/dubbo-desktop-manager#16]
![image](https://github.com/qiaolin-li/dubbo-desktop-manager/assets/6049187/33661629-d02c-4f94-b4d4-e20c80f920a7)
 显示的调用数据为0

**Comment by qiaolin-li** [comment]
你们是不是也用了nacos group功能啊

**Comment by MarvinYu** [comment]
> 你们是不是也用了nacos group功能啊

是的，这个有什么解决办法吗？

**Comment by qiaolin-li** [comment]
有，我到时候发一个新版本来支持它

**Comment by qiaolin-li** [comment]
![image](https://github.com/qiaolin-li/dubbo-desktop-manager/assets/32925394/52e26619-efdb-4f7f-b9e4-ae5b0f313931)
请问你们用的nacos group是指的第一个还是第二个啊！
还有就是你有没有配置代码，我好方便测试一下！！

**Comment by qiaolin-li** [comment]
已经支持了，可以自己设置group，服务的组和配置的组都可以支持了，
下载地址：https://github.com/qiaolin-li/dubbo-desktop-manager/releases/tag/v1.0.9
<img width="1200" alt="image" src="https://github.com/qiaolin-li/dubbo-desktop-manager/assets/32925394/9a3e665c-d1e4-4e21-ad82-cce73a217020">

**Comment by MarvinYu** [comment]
> 已经支持了，可以自己设置group，服务的组和配置的组都可以支持了， 下载地址：https://github.com/qiaolin-li/dubbo-desktop-manager/releases/tag/v1.0.9 <img alt="image" width="1200" src="https://private-user-images.githubusercontent.com/32925394/336882206-9a3e665c-d1e4-4e21-ad82-cce73a217020.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMTk2NTcsIm5iZiI6MTcxOTIxOTM1NywicGF0aCI6Ii8zMjkyNTM5NC8zMzY4ODIyMDYtOWEzZTY2NWMtZDFlNC00ZTIxLWFkODItY2NlNzNhMjE3MDIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDA4NTU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3NTAwNjMyM2ZmZTQzNTlmMDY2MWE2ZjA1NDQyMDk4NzBhZjEzNmMxN2QzMjM4NDMyOGU2MDE4YTQ1YWM0ODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.E5LdHSsLbqLC0Dv-YUDeB0xqdarrdCKK6889lkpSoKg">

我尝试了下，还是没有显示出来。我那里使用不对？

**Comment by qiaolin-li** [comment]
能看看你的nacos的配置和服务列表不，然后再看看你怎么配置的
