### ISSUE TITLE
连接有权限配置的zookeeper如何配置？

### ISSUE THREAD

**Issue by lians0** [qiaolin-li/dubbo-desktop-manager#17]
连接有权限配置的zookeeper如何配置？

**Comment by qiaolin-li** [comment]
目前是不支持的，因为我们没用到密码，所以能不能提供下你们的配置，方便我下个版本支持

**Comment by lians0** [comment]
> 目前是不支持的，因为我们没用到密码，所以能不能提供下你们的配置，方便我下个版本支持

你需要什么配置？zk的？

**Comment by qiaolin-li** [comment]
我看了下，应该不需要了，了解下zk的认证方式

**Comment by qiaolin-li** [comment]
已经支持了，下载最新的版本即可
<img width="1200" alt="image" src="https://github.com/qiaolin-li/dubbo-desktop-manager/assets/32925394/8962cc76-03bc-4457-a9f7-1dfa764a8b58">
下载地址：https://github.com/qiaolin-li/dubbo-desktop-manager/releases/tag/v1.0.9
