### ISSUE TITLE
只有消费者列表，提供者列表是空的

### ISSUE THREAD

**Issue by wtlihao** [qiaolin-li/dubbo-desktop-manager#20]
![image](https://github.com/qiaolin-li/dubbo-desktop-manager/assets/30258468/da974ce2-d34a-40a8-89c8-5c581375cf7d)

**Comment by wtlihao** [comment]
![image](https://github.com/qiaolin-li/dubbo-desktop-manager/assets/30258468/99abc774-17c9-45e3-8d7e-3e3d618492a2)
在原生的网页管理端是能显示的

**Comment by qiaolin-li** [comment]
你是哪个版本的dubbo-admin啊，你能打开F12，把提供者给出来的借口数据发给我不，我这边好查问题
